<h1><center>Scientific Computing-Lab Assignment 7</center></h1>
<h1><center>Python Programming - Linear Algebra in NumPy</center></h1>

<b>Note<b>
1. Don't copy from other assignments, you can refer codes available in internet.
2. For similar copies marks will be 0 (zero).
3. Try to complete all programs and display with given specifications
4. Give appropriate messages for outputs.
5. Marks will be awarded for good programming practices and proper display of results
6. Submit assignment in html(or pdf) format, with all questions, codes and outputs visible.
7. For given code snippets, you have to run it and modify if any comments are given
8. For Programming questions include the questions also
9. Assignment is complete only if 7 and 8 are included in submitting file
10. You can include other images, animations and sections of your choice to improve quality of assignment (optional)

## 1. Matrix and Vector Products

### 1.1 Dot Product, Inner Product and Outer Product

In [1]:
import time
start_time=time.time()
import numpy as np
print(np.dot(3,4))
print(np.dot([2, 3], [2, 3]))
print(np.dot([[2, 3]], [2, 3])) 
print(np.dot([2j, 3j], [2j, 3j]))
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]
print(np.dot(a,b)) #instead of 2*2 matrix give matrices of size 2000*2000(all values 1)
print(np.vdot(a,b)) #How vdot is working ?
print(np.inner(np.eye(10),3))
a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3,4,5,6])
print(np.outer(a,b))
print(np.inner(a,b)) #change b to np.array([1,2,3])
print("Execution time ",time.time()-start_time)

12
13
[13]
(-13+0j)
[[4 1]
 [2 2]]
6
[[3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]]
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
91
Execution time  0.24634051322937012


### 1.2 Matrix Multiplication, Trace, Diagonal and Transpose

In [2]:
import time
start_time=time.time()
import numpy as np
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]
c=7
print("Dot Product of a and b is ",np.dot(a,b))
print("Dot Product of a and c is ",np.dot(a,c))
print("Matrix a multiplied by Matrix b is ",np.matmul(a,b)) #instead of b give c
print("Trace of a is ",np.trace(a))
print("Diagonal elements of a ",np.diag(a))
print("Transpose of b",np.transpose(b))
print("Execution time ",time.time()-start_time)

Dot Product of a and b is  [[4 1]
 [2 2]]
Dot Product of a and c is  [[7 0]
 [0 7]]
Matrix a multiplied by Matrix b is  [[4 1]
 [2 2]]
Trace of a is  2
Diagonal elements of a  [1 1]
Transpose of b [[4 2]
 [1 2]]
Execution time  0.00099945068359375


### 1.3 Sum, Mean and Variance

In [3]:
import time
start_time=time.time()
import numpy as np
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]
print("Sum of b is ",np.sum(b))
print("Rowwise sum of b is ",np.sum(b,axis=1)) #Try axis=0
print("Average of b is ",np.mean(b))
print("Rowwise average of b is ",np.mean(b,axis=1)) #Try axis=0
print("Variance of b is ",np.var(b))
print("Rowwise variance of b is ",np.var(b,axis=1)) #Try axis=0
print("Execution time ",time.time()-start_time)

Sum of b is  9
Rowwise sum of b is  [5 4]
Average of b is  2.25
Rowwise average of b is  [2.5 2. ]
Variance of b is  1.1875
Rowwise variance of b is  [2.25 0.  ]
Execution time  0.003000497817993164


### 1.4 Kronecker Product

In [4]:
import time
start_time=time.time()
import numpy as np
print(np.kron(np.eye(2), np.ones((2,2))))
print("Execution time ",time.time()-start_time)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]
Execution time  0.0010008811950683594


## 2. Linear algebra Library

### 2.1 Power, Determinant, Inverse, Rank of a Matrix

In [5]:
import time
start_time=time.time()
import numpy as np 
a=np.array([[1 ,2],[1,4]])  #change [1,4] to [2,4]
print(np.linalg.matrix_power(a,3)) #Try 15 instead of 3
print(np.linalg.matrix_rank(a))
print(np.linalg.det(a)) #type output to int
print(np.linalg.inv(a))
print("Execution time ",time.time()-start_time)

[[13 46]
 [23 82]]
2
2.0
[[ 2.  -1. ]
 [-0.5  0.5]]
Execution time  0.010221481323242188


### 2.2 Solve the system of equations a + 2 * b = 1 and 3 * a + 5 * b = 2

In [6]:
import time
start_time=time.time()
import numpy as np 
A = np.array([[1, 2], [3, 5]]) #instead of [3,5] give [2,4]
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print(X)
a=X[0]
b=X[1]
print(a,b)
print(np.allclose(np.dot(A, X), B)) #checking whether solution is true
print("Execution time ",time.time()-start_time)

[-1.  1.]
-0.9999999999999994 0.9999999999999997
True
Execution time  0.0019998550415039062


### 2.3 Eigen Value and Eigen Vector

In [7]:
import time
start_time=time.time()
import numpy as np 
a=np.diag((1,2,3)) #change (1,2,3) to (1,2,3,4)
#a=np.array([[1,2],[3,4]]) Try this also
print(a)
w,v=np.linalg.eig(a)
print(w)
print(v)
print("Execution time ",time.time()-start_time)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Execution time  0.005001544952392578


## 3. Polynomials

### 3.1 Representing a polynomial and evaluating it's value

In [8]:
import time
start_time=time.time()
import numpy as np 
p = np.poly1d([1, 2, 3])
print(np.poly1d(p))
print(np.polyval(p,5))  #Evaluate polynomial at value 7
print(np.polyadd(p,p)) #try polysub, polydiv,polymul
print("Execution time ",time.time()-start_time)

   2
1 x + 2 x + 3
38
   2
2 x + 4 x + 6
Execution time  0.0009887218475341797


In [9]:
import time
start_time=time.time()
import numpy as np
p = np.poly1d([1, -2, 1]) #Design polynomial to produce imaginary roots
print(p.c)  #print coefficients of polynomial
print(np.roots(p))
print("Execution time ",time.time()-start_time)

[ 1 -2  1]
[1. 1.]
Execution time  0.001999378204345703


### 3.2 Least Square Polynomial fit

In [10]:
import time
start_time=time.time()
import numpy as np
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 2.0, 4.0, 6.0, 8.0, 10.0])  #Clearly y=2x
z = np.polyfit(x, y,1) #Change 1 to 2
print(z)
print(np.poly1d(z)(7))
print("Execution time ",time.time()-start_time)

[ 2.00000000e+00 -8.46295243e-17]
13.999999999999996
Execution time  0.0010004043579101562


## Write Python codes

1. Create 100 polynomials of following specification <br>
   First polynomial is x^99 + 1 <br>
   Second polynomial is x^99 + x <br>
   ..... <br>
   99'th polynomial is x^99 + x^98 <br>
   100'th polynomial is x^99 <br>
2. Store the coefficients to a matrix of size 100 * 100 <br>
3. Find rank of 100*100 matrix <br>
4. Write a function to extract any particular block in  that 100 *100 matrix <br>
5. Find the inverse of first 3 by 3 matrix(starting from 0,0) of that 100*100 matrix <br>

Note : You can use any logic, but output must be aligned with given specifications

# Solutions

In [ ]:
# Question 1
