# Python Programming - NumPy

In [27]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import time
import numpy as np
start_time=time.time()
a = np.array([1, 2, 3])
#Instead of [1,2,3] pass a list having 1000 values[1,...1000]
print(a)
print(a.shape)
print("Execution time ",time.time()-start_time)

[1 2 3]
(3,)
Execution time  0.0010004043579101562


In [2]:
import time
start_time=time.time()
import numpy as np 
a = np.array([[1, 2], [3, 4],[5,6]]) 
print(a)
print(a.shape)
a.shape = (2,3) 
print(a)
b = a.reshape(3,2) 
print(b)
print("Execution time ",time.time()-start_time)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
Execution time  0.0010023117065429688


In [3]:


import time
start_time=time.time()
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) #Try bool instead of complex
print(a)
print("Execution time ",time.time()-start_time)



[1.+0.j 2.+0.j 3.+0.j]
Execution time  0.000989675521850586


In [4]:
import time
start_time=time.time()
import numpy as np 
a = np.arange(24) 
print(a)
print(a.shape)
print(a.ndim)
b = a.reshape(2,4,3) #Try 5 instead of 3
print(b) 
print(b.shape)
print(b.ndim)
print("Execution time ",time.time()-start_time)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
(2, 4, 3)
3
Execution time  0.0020034313201904297


In [5]:


import time
start_time=time.time()
import numpy as np 
x = np.ones((5,4)) #Try ones instead of zeros
print(x)
print(x.shape)
print("Execution time ",time.time()-start_time)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(5, 4)
Execution time  0.000997781753540039


In [6]:
import time
start_time=time.time()
import numpy as np 
x = np.random.rand(5,4) 
print(x)
print(x.shape)
print("Execution time ",time.time()-start_time)

[[0.37774385 0.99359102 0.99402361 0.04191962]
 [0.34339658 0.82212937 0.56170538 0.64871124]
 [0.32697604 0.74126506 0.03986466 0.87801061]
 [0.76939387 0.14384918 0.05797777 0.10706538]
 [0.91865183 0.09564871 0.79351294 0.48449937]]
(5, 4)
Execution time  0.0009980201721191406


In [7]:
import time
start_time=time.time()
import numpy as np 
x = np.random.randint(100,size=(5,4)) 
print(x)
print(x.shape)
print("Execution time ",time.time()-start_time)

[[24 93 42 39]
 [80 74 73 73]
 [16  4 60 50]
 [51 27 36 58]
 [38  7  2 95]]
(5, 4)
Execution time  0.001001596450805664


In [8]:
import time
start_time=time.time()
import numpy as np
arr = np.array([1, 2, 3, 4, 5]) #Instead give a tuple(1,2,3,4,5)
print(arr)
print(type(arr))
print("Execution time ",time.time()-start_time)

[1 2 3 4 5]
<class 'numpy.ndarray'>
Execution time  0.000997304916381836


In [9]:
import time
start_time=time.time()
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) # Try arr[1,0,2]
print("Execution time ",time.time()-start_time)

6
Execution time  0.0010006427764892578


In [10]:
import time
start_time=time.time()
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1]) #Try arr[-3, -1]
print("Execution time ",time.time()-start_time)

Last element from 2nd dim:  10
Execution time  0.0


In [11]:
import time
start_time=time.time()
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) #Try arr[0:3]
print(arr[4:]) #Try arr[2:]
print(arr[:4]) #try arr[:1]
print(arr[-3:-1]) #Try arr[-5:-1]
print(arr[1:5:2]) #Try arr[1:6:4]
print(arr[::2]) #Try arr[::3]
print("Execution time ",time.time()-start_time)

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
Execution time  0.002000093460083008


In [12]:
import time
start_time=time.time()
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])
print("Execution time ",time.time()-start_time)

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
Execution time  0.0010004043579101562


In [13]:
import time
start_time=time.time()
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(bool)  #Try int instead of bool
print(newarr)
print(newarr.dtype)
print("Execution time ",time.time()-start_time)

[ True  True  True]
bool
Execution time  0.0009865760803222656


In [14]:
import time
start_time=time.time()
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)
print("Execution time ",time.time()-start_time)

[1 2 3]
[4 5 6]
Execution time  0.0010001659393310547


In [15]:
import time
start_time=time.time()
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)
print("Execution time ",time.time()-start_time)

1
2
3
4
5
6
Execution time  0.0


In [16]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr11 = np.concatenate((arr1, arr2))
print(arr11)
print("Execution time ",time.time()-start_time)

[1 2 3 4 5 6]
Execution time  0.31485891342163086


In [17]:
import time
start_time=time.time()
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
print("Execution time ",time.time()-start_time)

[[1 2 5 6]
 [3 4 7 8]]
Execution time  0.0


In [18]:
import time
start_time=time.time()
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
print("Execution time ",time.time()-start_time)

[[1 4]
 [2 5]
 [3 6]]
Execution time  0.0


In [19]:
import time
start_time=time.time()
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
print("Execution time ",time.time()-start_time)

[1 2 3 4 5 6]
Execution time  0.0010006427764892578


In [20]:
import time
start_time=time.time()
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)
print("Execution time ",time.time()-start_time)

[[1 2 3]
 [4 5 6]]
Execution time  0.0009980201721191406


In [23]:
import time
start_time=time.time()
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2) # check output by changing second argument to 3,4,5 and 6 
print(newarr)
print("Execution time ",time.time()-start_time)

[array([1, 2, 3]), array([4, 5, 6])]
Execution time  0.0010156631469726562


In [24]:
import time
start_time=time.time()
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 1)  #try 4 instead of 1
print(x)
print("Execution time ",time.time()-start_time)

(array([0], dtype=int64),)
Execution time  0.0009965896606445312


In [25]:
import time
start_time=time.time()
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0) #Try arr%4 == 0
print(x)
print("Execution time ",time.time()-start_time)

(array([1, 3, 5, 7], dtype=int64),)
Execution time  0.0009989738464355469


In [26]:
import time
start_time=time.time()
import numpy as np
arr = np.array([3, 2, 0, 1]) #Try [3,2,0,1.1]
print(np.sort(arr))
print("Execution time ",time.time()-start_time)

[0 1 2 3]
Execution time  0.0010013580322265625


In [27]:
import time
start_time=time.time()
import numpy as np
arr = np.array(['banana', 'cherry', 'apple']) #Try ['banana', '8herry', 'apple']
print(np.sort(arr))
print("Execution time ",time.time()-start_time)

['apple' 'banana' 'cherry']
Execution time  0.0010004043579101562


In [28]:
import time
start_time=time.time()
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42 #Try arr > 42 and arr < 44
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)
print("Execution time ",time.time()-start_time)

[False False  True  True]
[43 44]
Execution time  0.0010006427764892578


In [29]:
import time
start_time=time.time()
import numpy as np
arr = np.array([20, 8, 32, 36, 16]) #Try [20, 8, 32, 36.0, 16]
x = np.gcd.reduce(arr)
print(x)
print("Execution time ",time.time()-start_time)

4
Execution time  0.0


In [30]:
import time
start_time=time.time()
import numpy as np
arr = np.array([20, 8, 32, 36, 16])
x = np.lcm.reduce(arr)

print(x)
print("Execution time ",time.time()-start_time)

1440
Execution time  0.0009999275207519531


# Write Python code for the following problem

Create an array of 100 strings following specification

1. Each string has five alphabets (Ex: "AbHyM") randomly generated
2. First, Third and Fifth characters are Uppercase
3. Second and Fourth characters are Lowercase

After successful creation of the string do the following

1. Convert 100 strings to a single string and calculate alphabet frequency (like a-200.b-450,...z-90)
2. While calculating frequencies 'a' and 'A' are same
3. Create an array of size 26 with alphabet probabilities (if a-200, then p(a)=200/500, like that to z)

#### Answers